export enum Status {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  DONE = "DONE",
}

export enum IssueType {
  BUG = "BUG",
  TASK = "TASK",
  STORY = "STORY",
  EPIC = "EPIC",
  FEATURE = "FEATURE",
}

export enum Role {
  ADMIN = "ADMIN",
  DEVELOPER = "DEVELOPER",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  SUBMITTER = "SUBMITTER",
}

export enum NotificationType {
  ISSUE_CREATED = "ISSUE_CREATED",
  ISSUE_UPDATED = "ISSUE_UPDATED",
  ISSUE_DELETED = "ISSUE_DELETED",
  ISSUE_ASSIGNED = "ISSUE_ASSIGNED",
  COMMENT_CREATED = "COMMENT_CREATED",
  COMMENT_UPDATED = "COMMENT_UPDATED",
  COMMENT_DELETED = "COMMENT_DELETED",
  PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED",
  PROJECT_MEMBER_REMOVED = "PROJECT_MEMBER_REMOVED",
  PROJECT_MANAGER_ASSIGNED = "PROJECT_MANAGER_ASSIGNED",
  PROJECT_MANAGER_REMOVED = "PROJECT_MANAGER_REMOVED",
  PROJECT_ASSIGNED = "PROJECT_ASSIGNED",
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_UPDATED = "PROJECT_UPDATED",
  PROJECT_DELETED = "PROJECT_DELETED",
}

export enum Priority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}
